# Continuous deployment configuration
# See http://doc.gitlab.com/ci/builds_configuration/README.html
image: docker:latest

services:
- docker:dind

stages:
    - build
    - test
    - integration-test
    - release
    - deploy

variables:
    # When using dind, it's wise to use the overlayfs driver for
    # improved performance.
    DOCKER_DRIVER: overlay2
    GOOGLE_API_KEY: AIzaSyChNlerDt3cxNWvSylVdCsUkJ-3l87qojU
    ISS_URL: BACKEND_URL \
    SELENIUM_BROWSER: phantomjs
    ENVIRONMENT: staging
    CONTAINER_REGISTRY: "registry.gitlab.com/ferdinand-swoboda"
    APP: "askizzy-frontend"
    CONTAINER_TEST_IMAGE: ${CONTAINER_REGISTRY}/${APP}:${CI_COMMIT_SHA}
    CONTAINER_RELEASE_IMAGE: ${CONTAINER_REGISTRY}/${APP}:${CI_COMMIT_TAG}

before_script:
- docker login -u gitlab-ci-token -p $ACCESS_TOKEN $CONTAINER_REGISTRY

build:
    stage: build
    script:
    - docker build --pull -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE

unit-test:
    stage: test
    script:
    - docker run -t -e SELENIUM_BROWSER=${SELENIUM_BROWSER} -e GOOGLE_API_KEY=${GOOGLE_API_KEY} -e ENVIRONMENT=${ENVIRONMENT} -- ${CONTAINER_TEST_IMAGE} unit-test

release:
    stage: release
    script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker rmi $CONTAINER_TEST_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
    only:
    - tags

deploy:
    stage: deploy
    script: echo 'Now things should be deployed...'
    when: manual
    allow_failure: false
    only:
    - tags
