/* @flow */
/* Generated by ./script/iconify */
/* eslint-disable max-len */

import React from "react";
import classnames from "classnames";

export default class SvgIconSilver extends React.Component {
    props: {
        className?: string,
    };
    state: void;

    render() {
        const {className, ...rest} = this.props;
        const classes = classnames(
            "SilverIcon",
            "disallow-override-color",
            "Icon",
            "SvgIcon",
            className
        );

        return (
            <span
                {...rest}
                dangerouslySetInnerHTML={{__html: `
                    <svg class='${classes}' viewBox="0 0 69 75" fill="none" xmlns="http://www.w3.org/2000/svg"><rect width="69" height="74.9999" fill="black" fill-opacity="0"></rect><path d="M34.4334 59.5571C50.91 59.5571 64.2669 46.2248 64.2669 29.7785C64.2669 13.3323 50.91 0 34.4334 0C17.9569 0 4.6 13.3323 4.6 29.7785C4.6 46.2248 17.9569 59.5571 34.4334 59.5571Z" fill="#CDCDCD"></path><rect width="69" height="27.8888" fill="black" fill-opacity="0" transform="translate(0 47.1111)"></rect><path d="M10.265 47.1997L0 64.9605L11.9807 64.3257L17.4238 74.9999L26.9196 58.5678C20.1158 56.8109 14.2733 52.7214 10.265 47.1997Z" fill="#B30000"></path><path d="M58.6611 47.1111C54.6823 52.6475 48.8399 56.7518 42.0508 58.5382L51.5762 74.9999L57.0193 64.3257L69 64.9605L58.6611 47.1111Z" fill="#B30000"></path><path d="M34.4334 51.3631C46.3763 51.3631 56.0579 41.6994 56.0579 29.7785C56.0579 17.8576 46.3763 8.19385 34.4334 8.19385C22.4906 8.19385 12.809 17.8576 12.809 29.7785C12.809 41.6994 22.4906 51.3631 34.4334 51.3631Z" fill="#A5A5A5"></path><path d="M49.254 27.4459C49.9196 26.7962 49.5498 25.6594 48.6328 25.5266L40.0984 24.2864C39.7286 24.2274 39.418 24.0059 39.2553 23.6663L35.4392 15.9449C35.0251 15.1033 33.827 15.1033 33.4129 15.9449L29.6116 23.6663C29.4489 23.9911 29.1235 24.2274 28.7685 24.2864L20.2341 25.5266C19.317 25.6594 18.9473 26.7962 19.6129 27.4459L25.7807 33.4547C26.0469 33.7205 26.1653 34.0896 26.1061 34.4439L24.6566 42.9183C24.4939 43.8337 25.4701 44.5423 26.2984 44.0994L33.9305 40.0984C34.2559 39.9213 34.6553 39.9213 34.9807 40.0984L42.6129 44.0994C43.4412 44.5276 44.4026 43.8337 44.2547 42.9183L42.7904 34.4439C42.7312 34.0748 42.8495 33.7057 43.1158 33.4547L49.254 27.4459Z" fill="white"></path></svg>
                `}}
            />
        );
    }
}
