options:
files:
    include: 'src/**/*.s+(a|c)ss'
    ignore: ['src/styles/normalize.scss', 'src/styles/fonts.scss']
rules:
    border-zero: 2
    class-name-format: 0
    clean-import-paths: 2
    empty-args: 2
    empty-line-between-blocks: 2
    extends-before-declarations: 2
    extends-before-mixins: 2
    final-newline: 2
    force-element-nesting: 0
    force-pseudo-nesting: 0
    hex-length:
        - severity: 2
        - style: long
    hex-notation: 2
    indentation:
        - severity: 2
        - size: 4
    leading-zero:
        - 2
        - include: true
    mixin-name-format: 0
    mixins-before-declarations: 2
    # We use a lot of nesting.
    nesting-depth: 0
    no-color-keywords: 2
    no-color-literals: 2
    # Why would anyone ban comments?
    no-css-comments: 0
    no-debug: 2
    no-duplicate-properties: 2
    no-empty-rulesets: 2
    no-extends: 2
    no-ids: 2
    no-important: 2
    no-invalid-hex: 2
    no-mergeable-selectors: 0
    # Disabled because it reports vendor prefixes as misspellings
    # Re-enable once we upgrade to an autoprefixer that works for IE 10
    no-misspelled-properties: 0
    no-qualifying-elements: 0
    no-warn: 2
    no-vendor-prefixes: 0
    one-declaration-per-line: 2
    placeholder-in-extend: 2
    property-sort-order:
        - 2
        - order: smacss
    quotes:
        - 2
        - style: double
    single-line-per-selector: 2
    space-after-bang: 2
    space-after-colon: 2
    space-after-comma: 2
    space-around-operator: 0
    space-before-bang: 2
    space-before-brace: 2
    space-before-colon: 2
    space-between-parens: 2
    trailing-semicolon: 2
    variable-for-property: 2
    zero-unit: 2
