#!/usr/bin/env bash

# All the mock variables we need.
ENVIRONMENT="staging"
ISS_URL="http://localhost:5000"
GOOGLE_API_KEY="AIzaSyChNlerDt3cxNWvSylVdCsUkJ-3l87qojU"

export ENVIRONMENT
export ISS_URL
export GOOGLE_API_KEY

# Start the ISS server.
./script/mock-iss &
ISS_ID=$!

# Start the react server.
./script/dev-server &
REACT_ID=$!

trap interrupt INT

function interrupt() {
	if [[ "$OSTYPE" == "msys" ]] || [[ "$OSTYPE" == "cygwin" ]]; then
	    taskkill //IM node.exe //F
	else
		kill -9 $ISS_ID
		kill -9 $REACT_ID
	fi	
}

# Stay open
tail -f /dev/null