#!/usr/bin/env bash

# All the mock variables we need.
# Use environment variables if told to, otherwise use these defaults.
if [ "$1" != "--env" ]; then
	ENVIRONMENT="staging"
	ISS_URL="http://localhost:5000"
	FEEDBACK_URL="http://144.6.226.112/api"
	GOOGLE_API_KEY="AIzaSyChNlerDt3cxNWvSylVdCsUkJ-3l87qojU"
fi

export ENVIRONMENT
export ISS_URL
export FEEDBACK_URL
export GOOGLE_API_KEY

# Start the ISS server.
./script/mock-iss &
ISS_ID=$!

# Start the react server.
./script/dev-server &
REACT_ID=$!

trap interrupt INT

# a hook to kill the mock ISS and react server upon
# detection of the interrupt signal.
function interrupt() {
	if [[ "$OSTYPE" == "msys" ]] || [[ "$OSTYPE" == "cygwin" ]]; then
	    taskkill //IM node.exe //F
	else
		kill -9 $ISS_ID
		kill -9 $REACT_ID
	fi	
}

# Stay open
tail -f /dev/null
