#!/usr/bin/env bash
#
# Mock ISS server on port 5000
#
set -euo pipefail

IFS=$'\n\t'

if [[ "$OSTYPE" == "cygwin" ]] || [[ "$OSTYPE" == "msys" ]]; then
    PATH=$(echo "/$(npm bin)" | sed 's/\\/\//g' | sed 's/://'):$PATH
else
	PATH=`npm bin`:$PATH
fi

export NODE_ENV=development
export DEBUG=web

nodemon `dirname $0`/../test/support/mock_iss/index.js
