#!/usr/bin/env bash
set -euxo pipefail
IFS=$'\n\t'
PATH=$(npm bin):$PATH
CHAI_JEST_SNAPSHOT_UPDATE_ALL=false

count=1
for i in "$@" ; do
    if [[ $i == "--reset-snapshots" ]] ; then
        CHAI_JEST_SNAPSHOT_UPDATE_ALL=true
        set -- "${@:1:count-1}" "${@:count+1}"
    fi
    (( count++ ))
done

export NODE_ENV=production
export PORT=8010
export CHAI_JEST_SNAPSHOT_UPDATE_ALL

PAUSE_ON_ERROR= mocha --compilers js:babel-core/register test/unit.js $@
